# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import taskapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date_created', taskapp.models.ISODateTimeField(default=datetime.datetime.now)),
                ('done', models.BooleanField()),
            ],
        ),
    ]
